-- ============ SCHEMA 1: user_details ============

CREATE TABLE public.admin_front_ui (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  assigned_role character varying(64),
  assing_client_ids text,
  clientid integer,
  enabled_keys text,
  theme_name character varying(255)
);

CREATE TABLE public.ai_chat_service (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  answer text,
  confidence double precision,
  created_at timestamp(6) with time zone NOT NULL,
  human_correction text,
  merchant_id bigint,
  metadata_json text,
  question text,
  sensitive_flag boolean,
  session_id character varying(64),
  source_type character varying(16),
  status character varying(16) NOT NULL,
  updated_at timestamp(6) with time zone,
  user_role character varying(20) NOT NULL
);

CREATE TABLE public.announcement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  acquirer character varying(255),
  created_at timestamp(6) without time zone,
  is_archived boolean,
  message character varying(5000),
  priority character varying(255),
  tags character varying(255),
  target_audience character varying(255),
  title character varying(255),
  CONSTRAINT announcement_target_audience_check CHECK (target_audience IN ('ALL', 'ACTIVE', 'SUSPENDED'))
);

CREATE TABLE public.api_key_management (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  api_key text,
  api_secret text,
  base_url character varying(512),
  category character varying(32) NOT NULL,
  created_at timestamp(6) without time zone,
  created_by character varying(512),
  environment character varying(32) NOT NULL,
  extra_config_json text,
  is_default boolean NOT NULL,
  json_log_history text,
  mask_preview character varying(32),
  model_name character varying(128),
  project_id character varying(128),
  provider_name character varying(128) NOT NULL,
  region character varying(64),
  remarks character varying(1000),
  service_code character varying(64) NOT NULL,
  status boolean NOT NULL,
  updated_at timestamp(6) without time zone,
  updated_by character varying(512),
  CONSTRAINT api_key_management_service_code_environment_key UNIQUE (service_code, environment)
);

CREATE TABLE public.authorized_emails (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  active smallint,
  clientid integer,
  created_date timestamp(6) without time zone,
  email character varying(255),
  fullname character varying(255),
  "primary" smallint,
  role character varying(255),
  updated_date timestamp(6) without time zone,
  verifcode character varying(255)
);

CREATE TABLE public.bookmarks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  action_name character varying(64) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  data jsonb,
  entity_id integer,
  role character varying(32) NOT NULL,
  title character varying(128) NOT NULL,
  user_id integer NOT NULL
);

CREATE TABLE public.client_info_table (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  account_balance numeric(38,2),
  account_id character varying(255),
  account_number character varying(255),
  address character varying(1000),
  address2 character varying(1000),
  allow_currency character varying(255),
  allow_payout character varying(255),
  aml_compliant boolean,
  auto_refresh_dashboard boolean,
  business_activity character varying(1000),
  business_email character varying(255),
  business_type character varying(255),
  city character varying(255),
  common_bank_accounts character varying(255),
  compact_view boolean,
  company_address character varying(1000),
  company_name character varying(255),
  company_registration_number character varying(255),
  confirm_password character varying(255),
  contact character varying(255),
  contact_number character varying(255),
  country character varying(255),
  country_of_incorporation character varying(255),
  danger_zone boolean,
  dark_mode boolean,
  data_analytics boolean,
  data_processing boolean,
  data_retention character varying(255),
  date_of_birth character varying(255),
  date_of_incorporation character varying(255),
  dba character varying(255),
  default_currency character varying(255),
  default_language character varying(255),
  description character varying(1000),
  email character varying(255),
  employment_status character varying(255),
  enter_activity character varying(1000),
  export_account_data boolean,
  first_name character varying(255),
  gdpr_compliant boolean,
  gender character varying(255),
  google_auth_secret character varying(255),
  id_expiry_date character varying(255),
  id_number character varying(255),
  id_type character varying(255),
  individual_or_corporate character varying(255),
  industry character varying(255),
  is_account_linked character varying(255),
  json_upload_documents text,
  kyc_verified boolean,
  last_name character varying(255),
  legal_name character varying(255),
  marketing_communications boolean,
  name character varying(255),
  nationality character varying(255),
  password character varying(255),
  pci_compliant boolean,
  pincode character varying(255),
  place_of_birth character varying(255),
  profile_complete boolean,
  profile_img character varying(255),
  profile_visibility boolean,
  refund_url character varying(500),
  reset_all_settings boolean,
  reset_email_sent_time timestamp(6) without time zone,
  reset_password_time timestamp(6) without time zone,
  role_in_company character varying(255),
  roles character varying(255),
  session_timeout integer,
  show_time_display boolean,
  state character varying(255),
  status character varying(255),
  street character varying(255),
  support_email character varying(255),
  tax_id character varying(255),
  tc character varying(255),
  telegram_username character varying(255),
  timezone character varying(255),
  two_factor_enabled boolean,
  user_name character varying(255),
  verify_signup_otp character varying(255),
  website character varying(500),
  whatsapp_number character varying(255),
  agreement_signature text,
  agreement_signature_color character varying(255),
  agreement_signature_font character varying(255),
  agreement_signature_method character varying(255),
  agreement_signed_at timestamp(6) without time zone,
  dashboard_layout character varying(255),
  email_notifications boolean,
  sms_notifications boolean,
  theme_preference character varying(255),
  weekly_summary boolean,
  account_permissions_json jsonb,
  parent_id integer,
  sub_account_role character varying(64),
  admin_front_ui_id integer,
  allow_admin_list character varying(255),
  allow_merchant_list character varying(255),
  gateway_partner_id integer,
  host_id integer,
  merchant_front_ui_id integer
);

CREATE TABLE public.currency (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  code character varying(255),
  flags character varying(255),
  icon character varying(255),
  is_default boolean,
  name character varying(255),
  status character varying(255),
  territory character varying(255)
);

CREATE TABLE public.email_temp_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  code character varying(255),
  email_message text,
  email_subject character varying(255)
);

CREATE TABLE public.faq_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  answer text NOT NULL,
  category character varying(100),
  created_at timestamp(6) without time zone NOT NULL,
  keywords text,
  question text NOT NULL,
  updated_at timestamp(6) without time zone,
  image_url text,
  video_url text
);

CREATE TABLE public.front_ui (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  assing_client_ids text,
  clientid integer,
  enabled_keys text,
  theme_name character varying(255)
);

CREATE TABLE public.hosting_detail (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  address character varying(255),
  contact character varying(255),
  email character varying(255),
  header_color character varying(255),
  logo character varying(255),
  long_name character varying(255),
  short_name character varying(255),
  sidebar_color character varying(255),
  smtp_host character varying(255),
  smtp_password character varying(255),
  smtp_port integer NOT NULL,
  smtp_username character varying(255)
);

CREATE TABLE public.mcc_code (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  category_key character varying(255),
  category_name character varying(255),
  category_status boolean,
  cdate timestamp(6) without time zone,
  comments character varying(255),
  json_log_history character varying(255),
  mcc_code character varying(255)
);

CREATE TABLE public.merchant_announcement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  announcement_id bigint NOT NULL,
  delivered_at timestamp(6) without time zone,
  is_archived boolean,
  is_read boolean,
  read boolean,
  user_id integer NOT NULL
);

CREATE TABLE public.merchant_referral (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp(6) without time zone NOT NULL,
  merchant_id integer NOT NULL,
  referral_code character varying(32) NOT NULL,
  updated_at timestamp(6) without time zone NOT NULL,
  CONSTRAINT merchant_referral_referral_code_key UNIQUE (referral_code),
  CONSTRAINT merchant_referral_merchant_id_key UNIQUE (merchant_id)
);

CREATE TABLE public.merchant_service_application_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  form_type character varying(40) NOT NULL,
  payload jsonb,
  submitted_at timestamp(6) without time zone NOT NULL,
  request_id bigint NOT NULL,
  CONSTRAINT merchant_service_application_data_request_id_key UNIQUE (request_id)
);

CREATE TABLE public.merchant_service_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  activated_at timestamp(6) without time zone,
  company_name character varying(255),
  created_at timestamp(6) without time zone NOT NULL,
  merchant_id integer NOT NULL,
  rejected_at timestamp(6) without time zone,
  rejection_reason text,
  requested_at timestamp(6) without time zone NOT NULL,
  reviewed_by_admin_id integer,
  status character varying(20) NOT NULL,
  updated_at timestamp(6) without time zone NOT NULL,
  service_id bigint NOT NULL,
  CONSTRAINT merchant_service_requests_status_check CHECK (status IN ('pending', 'active', 'rejected', 'suspended')),
  CONSTRAINT merchant_service_requests_merchant_id_service_id_key UNIQUE (merchant_id, service_id)
);

CREATE TABLE public.mop_connector_icon (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  cdate timestamp(6) without time zone,
  comments character varying(2000),
  icon_name character varying(240),
  icon_type character varying(50),
  mop_name character varying(400),
  mop_status integer,
  mop_type character varying(150)
);

CREATE TABLE public.multi_domains_map (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  admin_front_ui_id integer,
  backend_api_domain_name character varying(255),
  cdate timestamp(6) without time zone,
  developer_url character varying(500),
  domain_brand_name character varying(255),
  domain_status character varying(32),
  domains_name character varying(255),
  email_api character varying(32),
  email_api_key_json text,
  favicon_file_name character varying(500),
  frontend_domain_name character varying(255),
  logo_file_name character varying(500),
  main_domain_name character varying(255),
  merchant_front_ui_id integer,
  support_email character varying(255),
  support_no character varying(64),
  udate timestamp(6) without time zone,
  checkout_base_url character varying(500),
  cors_allowed_origins text,
  otp_auth_urls text
);

CREATE TABLE public.referral_commission (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  commission_amount numeric(18,2) NOT NULL,
  commission_type character varying(20) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  currency character varying(10) NOT NULL,
  referral_id bigint NOT NULL,
  status character varying(20) NOT NULL
);

CREATE TABLE public.referral_invitation (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email character varying(255),
  invite_type character varying(20) NOT NULL,
  referrer_id integer NOT NULL,
  sent_at timestamp(6) without time zone NOT NULL,
  status character varying(20) NOT NULL
);

CREATE TABLE public.referral_mapping (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp(6) without time zone NOT NULL,
  earned_commission numeric(18,2) NOT NULL,
  fraud_reason character varying(500),
  fraud_status character varying(20),
  referred_merchant_id integer NOT NULL,
  referred_signup_ip character varying(64),
  referrer_id integer NOT NULL,
  status character varying(20) NOT NULL,
  total_volume numeric(18,2) NOT NULL,
  updated_at timestamp(6) without time zone NOT NULL,
  CONSTRAINT referral_mapping_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED')),
  CONSTRAINT referral_mapping_referred_merchant_id_key UNIQUE (referred_merchant_id)
);

CREATE TABLE public.referral_mapping_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  allow_self_referral boolean NOT NULL,
  auto_approval_limit numeric(18,2),
  block_same_device boolean NOT NULL,
  block_same_email boolean NOT NULL,
  block_same_ip boolean NOT NULL,
  block_same_kyc boolean NOT NULL,
  block_same_mobile boolean NOT NULL,
  commission_amount numeric(18,2) NOT NULL,
  commission_frequency character varying(20) NOT NULL,
  commission_trigger character varying(40) NOT NULL,
  commission_type character varying(30) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  currency character varying(10) NOT NULL,
  max_referrals_per_merchant integer,
  maximum_commission_cap numeric(18,2),
  maximum_transactions integer,
  maximum_volume numeric(18,2),
  maximum_withdrawal numeric(18,2),
  min_transaction_amount numeric(18,2) NOT NULL,
  minimum_commission numeric(18,2),
  minimum_transactions integer,
  minimum_volume numeric(18,2),
  minimum_withdrawal numeric(18,2) NOT NULL,
  program_name character varying(120),
  program_status character varying(20) NOT NULL,
  recurring_amount numeric(18,2),
  recurring_months integer,
  referral_code_prefix character varying(20),
  referral_expiry_days integer NOT NULL,
  referral_mapping_id bigint NOT NULL,
  terms_and_conditions_url character varying(500),
  updated_at timestamp(6) without time zone NOT NULL,
  volume_currency character varying(10),
  withdrawal_fee numeric(18,2),
  withdrawal_fee_type character varying(20),
  CONSTRAINT referral_mapping_config_referral_mapping_id_key UNIQUE (referral_mapping_id)
);

CREATE TABLE public.referral_payout (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  amount numeric(18,2) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  currency character varying(10) NOT NULL,
  merchant_id integer NOT NULL,
  status character varying(20) NOT NULL,
  transaction_id character varying(64)
);

CREATE TABLE public.referral_wallet (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  available_balance numeric(18,2) NOT NULL,
  merchant_id integer NOT NULL,
  pending_balance numeric(18,2) NOT NULL,
  updated_at timestamp(6) without time zone NOT NULL,
  CONSTRAINT referral_wallet_merchant_id_key UNIQUE (merchant_id)
);

CREATE TABLE public.referral_wallet_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  after_balance numeric(18,2) NOT NULL,
  amount numeric(18,2) NOT NULL,
  before_balance numeric(18,2) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  reference_id character varying(64),
  transaction_type character varying(30) NOT NULL,
  wallet_id bigint NOT NULL
);

CREATE TABLE public.services_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  activation_flow_type character varying(30) NOT NULL,
  activation_type character varying(30) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  currency character varying(8) NOT NULL,
  description text NOT NULL,
  display_order integer NOT NULL,
  features jsonb,
  icon character varying(60) NOT NULL,
  is_active boolean NOT NULL,
  name character varying(120) NOT NULL,
  price numeric(12,2) NOT NULL,
  price_label character varying(120),
  price_type character varying(40) NOT NULL,
  route_path character varying(120),
  service_category character varying(40) NOT NULL,
  short_description text,
  slug character varying(80) NOT NULL,
  updated_at timestamp(6) without time zone NOT NULL,
  CONSTRAINT services_catalog_activation_flow_type_check CHECK (activation_flow_type IN ('instant', 'simple_approval', 'kyc_required', 'otc_request')),
  CONSTRAINT services_catalog_activation_type_check CHECK (activation_type IN ('instant', 'approval_required')),
  CONSTRAINT services_catalog_slug_key UNIQUE (slug)
);

CREATE TABLE public.support_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  category character varying(255),
  client_id integer,
  created_at timestamp(6) without time zone,
  is_read boolean,
  message_id character varying(255),
  message_text text,
  message_text_hash character varying(255),
  priority character varying(255),
  sender_type character varying(255),
  status character varying(255),
  subject character varying(255),
  upload_documents text,
  user_name character varying(255)
);

CREATE TABLE public.user_account (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  account_balance numeric(38,2),
  account_number character varying(255),
  currency character varying(255),
  status character varying(255),
  user_id character varying(255)
);

-- ============ SCHEMA 2: transaction ============

CREATE TABLE public.flyway_schema_history (
  installed_rank integer NOT NULL PRIMARY KEY,
  version character varying(50),
  description character varying(200) NOT NULL,
  type character varying(20) NOT NULL,
  script character varying(1000) NOT NULL,
  checksum integer,
  installed_by character varying(100) NOT NULL,
  installed_on timestamp without time zone DEFAULT now() NOT NULL,
  execution_time integer NOT NULL,
  success boolean NOT NULL
);

CREATE TABLE public.master_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  available_balance double precision,
  available_rolling double precision,
  bank_processing_amount double precision,
  bank_processing_curr text,
  bearer_token bigint,
  bill_amt double precision,
  bill_currency character varying(255),
  bill_email text,
  bill_ip text,
  buy_mdr_amt double precision,
  buy_txnfee_amt double precision,
  channel_type integer,
  connector bigint,
  created_date timestamp(6) without time zone,
  default_currency_amount double precision,
  fee_id integer,
  fee_update_timestamp timestamp(6) without time zone,
  fullname text,
  gst_amt double precision,
  immature_rolling_fund_amt double precision,
  integration_type text,
  mature_rolling_fund_amt double precision,
  mdr_cbk1_amt double precision,
  mdr_cb_amt double precision,
  mdr_refundfee_amt double precision,
  merid bigint,
  mop text,
  mop_name text,
  payable_amt_of_txn double precision,
  reference text,
  related_transid text,
  remaining_balance_amt double precision,
  remark_status smallint,
  risk_ratio text,
  rolling_amt double precision,
  rolling_date timestamp(6) without time zone,
  rolling_delay integer,
  runtime integer,
  sell_mdr_amt double precision,
  sell_txnfee_amt double precision,
  settelement_date timestamp(6) without time zone,
  settelement_delay integer,
  terno bigint,
  transid bigint,
  trans_amt double precision,
  trans_currency character varying(255),
  tdate timestamp(6) without time zone,
  transaction_flag character varying(255),
  transaction_period text,
  trans_status smallint,
  trans_status_step smallint,
  trans_type integer,
  parent_trans_id bigint,
  attempt_number integer DEFAULT 1,
  is_orchestration_child boolean DEFAULT false,
  CONSTRAINT master_transaction_transid_key UNIQUE (transid)
);

CREATE TABLE public.master_transaction_additional (
  id_ad bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  authdata text,
  authurl character varying(255),
  authentication_type character varying(115),
  bill_address text,
  bill_city text,
  bill_country text,
  bill_phone text,
  bill_state text,
  bill_zip text,
  bin_no integer,
  card_brand character varying(115),
  ccno text,
  card_tier character varying(115),
  card_type character varying(115),
  connector_creds_processing_final text,
  connector_json text,
  connector_payload_stage1 text,
  connector_payload_stage2 text,
  connector_payload_stage3 text,
  connector_ref character varying(255),
  connector_response text,
  connector_response_stage1 text,
  connector_response_stage2 text,
  customer_device_type character varying(115),
  descriptor character varying(255),
  ex_month text,
  ex_year text,
  gateway character varying(115),
  issuing_bank character varying(215),
  issuing_country character varying(50),
  json_log_history text,
  "json_value" text,
  mer_note text,
  payload_stage1 text,
  product_name text,
  return_url character varying(255),
  routing_channel character varying(115),
  rrn character varying(255),
  source_url character varying(255),
  support_note text,
  system_note text,
  transid_ad bigint,
  trans_response text,
  upa character varying(255),
  webhook_url character varying(255),
  payload_stage2 text,
  webhook_response_history_json text,
  webhook_response_stage1 text,
  orchestration_json text,
  orchestration_attempt_count integer
);

CREATE TABLE public.terminal_report_delivery_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp(6) without time zone,
  error_message text,
  merchant_id integer,
  period_end timestamp(6) without time zone,
  period_start timestamp(6) without time zone,
  recipient_email character varying(255),
  recipient_name character varying(255),
  report_format character varying(255),
  report_type character varying(255),
  retry_count integer,
  sent_at timestamp(6) without time zone,
  status character varying(255),
  terminal_id integer
);

-- ============ GRANTS + RLS (locked to API layer; service_role only) ============

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'admin_front_ui','ai_chat_service','announcement','api_key_management','authorized_emails',
    'bookmarks','client_info_table','currency','email_temp_details','faq_entries','front_ui',
    'hosting_detail','mcc_code','merchant_announcement','merchant_referral',
    'merchant_service_application_data','merchant_service_requests','mop_connector_icon',
    'multi_domains_map','referral_commission','referral_invitation','referral_mapping',
    'referral_mapping_config','referral_payout','referral_wallet','referral_wallet_transaction',
    'services_catalog','support_messages','user_account','flyway_schema_history',
    'master_transaction','master_transaction_additional','terminal_report_delivery_log'
  ]
  LOOP
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;